export const initialBlocks = [
  {
    number: 1,
    index: 1,
    position: { x: 0, y: 0 },
    initialDimensions: { width: 300, height: 100 },
    onBlockClick: () => {},
    updateBlockIndex: () => {},
    onBlockClose: () => {},
  },
  {
    number: 2,
    index: 2,
    position: { x: 412, y: 0 },
    initialDimensions: { width: 300, height: 100 },
    onBlockClick: () => {},
    updateBlockIndex: () => {},
    onBlockClose: () => {},
  },
  {
    number: 3,
    index: 3,
    position: { x: 824, y: 0 },
    initialDimensions: { width: 300, height: 100 },
    onBlockClick: () => {},
    updateBlockIndex: () => {},
    onBlockClose: () => {},
  },
  {
    number: 4,
    index: 4,
    position: { x: 210, y: 189 },
    initialDimensions: { width: 300, height: 100 },
    onBlockClick: () => {},
    updateBlockIndex: () => {},
    onBlockClose: () => {},
  },
  {
    number: 5,
    index: 5,
    position: { x: 622, y: 189 },
    initialDimensions: { width: 300, height: 100 },
    onBlockClick: () => {},
    updateBlockIndex: () => {},
    onBlockClose: () => {},
  },
];
